### ISSUE TITLE
法一 await 是否可執行？

### ISSUE THREAD

**Issue by azole** [ycchien313/nodejs-mfee16#1]
https://github.com/ycchien313/nodejs-mfee16/blob/fc79c64036948ee781a922d7354678ec1de50a07/basic/callback1.js#L11

這個法一有測試過是可以執行的嗎？

**Comment by ycchien313** [comment]
https://github.com/ycchien313/nodejs-mfee16/blob/master/basic/synchronous.js

老師，我覺得之前的檔案很亂，所以把它刪了，想改成以上之檔案，並以 Line 44 那邊繳交「callback 刷牙/早餐/寫功課」之作業

**Comment by ycchien313** [comment]
老師，那這邊的issue可以關了嗎0.0?

**Comment by azole** [comment]
可以～
