### ISSUE TITLE
這裡不用 return 可以嗎？

### ISSUE THREAD

**Issue by azole** [ycchien313/nodejs-mfee16#2]
https://github.com/ycchien313/nodejs-mfee16/blob/fddf3caea0f56397e3ce28dc5b20636e50093a2a/crawler/app.js#L18

請教一下這裡不用 return 是可以的嗎？
下一個 then 會接到什麼 response 呢？

**Comment by ycchien313** [comment]
不用 return 的話會接不到 getStockNo() 要回傳的 value。
老師說的下一個 then 我有點不清楚是指什麼..，我重新 push 一個不用 return 的 code 上去，老師再查閱一下，謝謝老師~!

**Comment by azole** [comment]
我這邊比較期望你們練習的是可以做出 promise chain，而不是把 axios 這個包在 getStockNo.then 裡頭做完。

換句話說，就是希望 return axios.get ，然後做出 promise chain 來，例如： （比較看看下列的結構跟你目前的寫法上的差異為何？）

```javascript
getStockNo
  .then((result) => {
    let stockNo = null;
    stockNo = result; //股票代碼

    return axios(config);
  })
  .then((response) => {
    let stockName = response.data["title"].split(/\s+/)[2];
    console.log(`股票名稱：${stockName}`);
  })
  .catch((err) => {
    console.log(`讀檔錯誤：${err}`);
  });

```

**Comment by ycchien313** [comment]
(fs.readFile promise)
https://github.com/ycchien313/nodejs-mfee16/blob/master/crawler/app.js

老師，我修改程式碼重新 push 上去了

**Comment by azole** [comment]
做得很好，可以關 issue～
