### ISSUE TITLE
試試看印出來 stockNo 是什麼？

### ISSUE THREAD

**Issue by azole** [ycchien313/nodejs-mfee16#3]
https://github.com/ycchien313/nodejs-mfee16/blob/3aa0599699cb3bbb768bb6729803e194ded5c8ed/crawler/app-await.js#L16

```javascript
    try {
        stockNo = await getStockNo
    } catch (err) {
        console.log("讀檔失敗", err)
        return
    }
```
getStockNo 應該是個函式？ 所以是不是應該要這樣呢？ ` stockNo = await getStockNo()`

**Comment by ycchien313** [comment]
getStockNo 我是寫成變數方式，不是 function，所以寫成 stockNo = await getStockNo() 會有問題

**Comment by azole** [comment]
了解了，謝謝！
