### ISSUE TITLE
axios 也是一個 promise，也可以被 await

### ISSUE THREAD

**Issue by azole** [ycchien313/nodejs-mfee16#4]
https://github.com/ycchien313/nodejs-mfee16/blob/3aa0599699cb3bbb768bb6729803e194ded5c8ed/crawler/app-await.js#L22

**Comment by ycchien313** [comment]
那.. 我加上 await 了 (應該是這樣吧..) 謝謝老師~

**Comment by ycchien313** [comment]
老師，我重新修正程式碼並 push 上去了，還請老師再幫忙查看，謝謝!

**Comment by azole** [comment]
很棒，結構整理得很好！
