### ISSUE TITLE
不愧是捷哥，好猛阿...

### ISSUE THREAD

**Issue by luofungyi** [ycchien313/nodejs-mfee16#5]
https://github.com/ycchien313/nodejs-mfee16/blob/6e344ab141e2ff34106edd30f2b558fce888e169/basic/promise-reject.js#L121

**Comment by ycchien313** [comment]
乾.. 這只是慢慢觀察.. 你慢慢觀察也可以的..

而且 issue 明明是提問題，被你搞得像發表心得..
